#:kivy 2.1.0

<Button>:
    background_normal:''
    background_color: (2/255,10/255,24/250)
    font_size: 32
    
<Calculator_by_PranavWidget>:

    BoxLayout:

        orientation: 'vertical'
        size: root.width, root.height

        TextInput:
            text:"0"
            font_size: "45"
            multiline: False
            halign: "right"
            size_hint:(1,0.18)
            valign: "centre"
            background_color: (2/255,10/255,24/255)
            id: input_box
            foreground_color:(1,1,1,1)
        
        GridLayout:
            cols: 4
            rows: 5

            Button:
                text:"%"
                on_press: root.sign("%")
            Button:
                text: "AC"
                on_press: root.clear()

            Button:
                text:u"\u00AB"
                on_press: root.backspace()
            Button:
                text: "÷"
                background_color:(15/255, 119/255, 184/255)
                on_press: root.sign("/")
            #### ROW 2 ####
            Button:
                text:"7"
                on_press: root.button_value("7")
            Button:
                text: "8"
                on_press: root.button_value("8")
            Button:
                text:"9"
                on_press: root.button_value("9")
            Button:
                text: "x"
                background_color:(15/255, 119/255, 184/255)
                on_press: root.sign("x")
            ####ROW 3####
            Button:
                text:"4"
                on_press: root.button_value("4")
            Button:
                text: "5"
                on_press: root.button_value("5")
            Button:
                text:"6"
                on_press: root.button_value("6")
            Button:
                text: "-"
                background_color:(15/255, 119/255, 184/255)
                on_press: root.sign("-")
                #### ROW 4####
            Button:
                text:"1"
                on_press: root.button_value("1")
            Button:
                text: "2"
                on_press: root.button_value("2")
            Button:
                text:"3"
                on_press: root.button_value("3")
            Button:
                text: "+"
                background_color:(15/255, 119/255, 184/255)
                on_press: root.sign("+")
            ####ROW 5####
            Button:
                text:"+/-"
            Button:
                text: "0"
                on_press: root.button_value("0")
            Button:
                text:"."
                on_press: root.decimal()
            Button:
                text: "=" 
                background_color:(15/255, 119/255, 184/255) 
                on_press: root.calculation()          
